### ISSUE TITLE
Super useful tool - saved my monorepo from chaos.

### ISSUE THREAD

**Issue by hhtpcd** [brendanjryan/modmerge#1]
Not an issue, but couldn't find another way to 👍 the project! Have been wrestling multiple go projects in a monorepo + bazel for a while and have been looking for a way to merge all dependencies and this is _exactly_ what I was after. Thanks man! 🚀

**Comment by brendanjryan** [comment]
@hhtpcd thank you! This was originally written for a project which sounds _exactly_ the same so i'm glad it worked for you as well!
